NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.airline.flight.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.airline.flight.com-cert.pem
    OrganizationalUnitIdentifier: peer
